services:
  api:
    build: .
    restart: unless-stopped
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/api-kanban
      SPRING_DATASOURCE_USERNAME: liron
      SPRING_DATASOURCE_PASSWORD: kanban
    networks:
      - dokploy-network

  db:
    image: postgres:18
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: liron
      POSTGRES_PASSWORD: kanban
      POSTGRES_DB: api-kanban
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liron -d api-kanban"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - dokploy-network

volumes:
  postgres_data:

networks:
  dokploy-network:
    external: true
